name: Deploy Template

on:
  workflow_call:
    inputs:
      workspace:
        required: true
        type: string

jobs:
  ########################################
  # PLAN
  ########################################
  plan:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: azure

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
      - name: Checkout Caller Repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Select Workspace
        run: |
          terraform workspace select ${{ inputs.workspace }} || \
          terraform workspace new ${{ inputs.workspace }}

      - name: Terraform Plan
        run: |
          terraform plan \
          -var-file=envs/${{ inputs.workspace }}.tfvars \
          -out=tfplan

      - name: Upload Plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: azure/tfplan

  ########################################
  # APPLY (WITH APPROVAL)
  #########################################
  apply:
    needs: plan
    runs-on: ubuntu-latest

    environment: tf-approve  

    defaults:
      run:
        working-directory: azure

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
      - name: Checkout Caller Repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Select Workspace
        run: |
          terraform workspace select ${{ inputs.workspace }} || \
          terraform workspace new ${{ inputs.workspace }}

      - name: Download Plan
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: azure

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
